#yml  文件不能使用制表空格tab    
#设置值只能使用 :(空格)值
server:
 port: 8080
 
 
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/park?serverTimezone=UTC&CharacterEncoding=UTF-8&useSSL=false
    username: root
    password: a
    driver-class-name: com.mysql.jdbc.Driver
    

#日志配置
logging:
   level:
      com:
         zhi:
           zblog:
               dao: debug
               web: warn 
